WITH CTE AS (
SELECT 
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

{{day_type('STARTED_AT')}} DAY_TYPE,

{{get_season('STARTED_AT')}} STATION_OF_YEAR,

MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT

from
{{ ref('stg_bike') }}
WHERE STARTED_AT != 'started_at'

)

SELECT * FROM CTE